# Generated by Django 3.2.2 on 2021-05-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regusers',
            fields=[
                ('user_num', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=8)),
                ('mpin', models.CharField(max_length=4)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
