# Generated by Django 3.2.2 on 2021-06-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_num', models.CharField(max_length=10)),
                ('transaction', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('agent', models.CharField(max_length=10, null=True)),
                ('recipient', models.CharField(max_length=10, null=True)),
                ('paybill', models.CharField(max_length=10, null=True)),
                ('account', models.CharField(max_length=10, null=True)),
                ('trans_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
