# Generated by Django 3.2.2 on 2021-06-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20210629_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='code',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
