# Generated by Django 3.2.2 on 2021-06-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20210629_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='transaction',
            field=models.CharField(max_length=15),
        ),
    ]
