# Generated by Django 3.2.2 on 2021-06-30 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210531_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agentnum', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('agentname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AgentAcount',
            fields=[
                ('agentnum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='agent', serialize=False, to='accounts.agent')),
                ('agentfloat', models.FloatField()),
            ],
        ),
    ]
