# Generated by Django 3.2.2 on 2021-06-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_statement_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='trans_cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statement',
            name='trans_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
