# Generated by Django 3.2.2 on 2021-05-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_num', models.CharField(max_length=10)),
                ('notif', models.CharField(max_length=150)),
                ('ifread', models.IntegerField()),
            ],
        ),
    ]
