# Generated by Django 3.2.2 on 2021-05-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210512_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='id',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='user_num',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
