# Generated by Django 3.2.2 on 2021-05-25 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210525_1035'),
        ('accounts', '0005_alter_accounts_user_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='user_num',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.regusers'),
        ),
    ]
